### ISSUE TITLE
Adicionar nome como colaborador

### ISSUE THREAD

**Issue by Milenamelotavares** [Milenamelotavares/-GCMS-Milena-Tavares#1]
[README](https://github.com/Milenamelotavares/-GCMS-Milena-Tavares/edit/main/README.md)

**Comment by ramidedantas** [comment]
@Milenamelotavares tá dando 404 no link. Veja se está correto.

**Comment by Milenamelotavares** [comment]
@ramidedantas corrigido professor!

**Comment by ramidedantas** [comment]
@Milenamelotavares tem um espaço entre o ] e (

**Comment by Milenamelotavares** [comment]
@ramidedantas corrigido!

**Comment by ramidedantas** [comment]
@Milenamelotavares coloque no formato que está no meu repositório.

**Comment by Milenamelotavares** [comment]
@ramidedantas coloquei professor!

**Comment by ramidedantas** [comment]
@Milenamelotavares pronto, pode fechar.
